### ISSUE TITLE
State information ?

### ISSUE THREAD

**Issue by motor-x** [rh20t/rh20t_api#11]
Hi,

Could you please let me know which file include the state and action information? 

I know there are:

joint.npy
tcp.npy

but, it seems that they are all representing state, right? Then, where to find the action?

Thanks!

**Comment by Galaxies99** [comment]
Hi,

`joint.npy` and `tcp.npy` are the joint positions and the end-effector pose (tool-center point pose), respectively. 

For the current timestep `t`, it is the proprioceptive state information of the robot. Actions can be obtained by reading the proprioceptive information of the next several timesteps `t+1, t+2, ..., t+H`, where `H` is the action horizon. You can also subsample the action sequences to make the action more obvious since the data were recorded at 10Hz.

For the gripper, the `gripper_info.npy` is the state of the gripper, and the `gripper_action.npy` is the action of the gripper. For each timestamp in both files, using only the first value (gripper width) is enough.

**Comment by hai-h-nguyen** [comment]
How about the information stored in `robot_command`? I checked and the time length there, and it is not the same as the time length in `transformed/joint.npy`. I am using `RH20T_cfg3`.
