### ISSUE TITLE
Gripper Command and Info 

### ISSUE THREAD

**Issue by AnqiLi** [rh20t/rh20t_api#9]
Hello, 

Thank you for sharing the dataset and codebase. I am wondering what information is stored in `gripper_command` and `gripper_info` in `gripper.npy`. According to the [website](https://rh20t.github.io), the first element is the actual gripper width in millimeters (0-110), but what about the other two?

For example, if I load from `RH20T_cfg1/task_0010_user_0012_scene_0003_cfg_0001/transformed/gripper.npy`, the entry corresponds to `cam_038522063145` and timestamp `1630825420947` is given by,
```
{'gripper_command': [95.0, 30, 1630825413966], 'gripper_info': [95.0, 65535, 1]}
```
what are `30`, `1630825413966`, `65535` and `1` standing for?

**Comment by Galaxies99** [comment]
It depends on different types of grippers. We recommend only using the first value (gripper width) since it is unified across different types of grippers.

*e.g.*, for Dahuan gripper (cfg1, 2):
- `gripper_info`: width, current, gripper state (see Dahuan AG-95 manual for details);
- `gripper_command`: width, force, timestamp for the last action.
